locals {
  is_flex = length(regexall("Flex", var.oci_shape)) > 0
}

data "oci_identity_availability_domains" "ads" {
  compartment_id = var.oci_compartment_ocid
}

data "oci_core_images" "ol8" {
  compartment_id           = var.oci_compartment_ocid
  operating_system         = "Oracle Linux"
  operating_system_version = "8"
  shape                    = var.oci_shape
  sort_by                  = "TIMECREATED"
  sort_order               = "DESC"
}

# ---------------- Network ----------------
resource "oci_core_vcn" "this" {
  compartment_id = var.oci_compartment_ocid
  cidr_blocks    = [var.oci_vcn_cidr]
  display_name   = "oci-aws-vcn"
}

resource "oci_core_internet_gateway" "igw" {
  compartment_id = var.oci_compartment_ocid
  vcn_id         = oci_core_vcn.this.id
  display_name   = "oci-aws-igw"
}

# ---------------- DRG ----------------
resource "oci_core_drg" "this" {
  compartment_id = var.oci_compartment_ocid
  display_name   = "oci-aws-drg"
}

# IMPORTANT: no drg_route_table_id set -> the attachment uses the default
# "Autogenerated Drg Route Table for VCN attachments". Custom DRG route tables
# broke route import between VCN and IPSec attachments in the manual build.
resource "oci_core_drg_attachment" "vcn" {
  drg_id       = oci_core_drg.this.id
  display_name = "oci-aws-vcn-attachment"

  network_details {
    id   = oci_core_vcn.this.id
    type = "VCN"
  }
}

# Subnet route table: internet + AWS CIDR via DRG
resource "oci_core_route_table" "public" {
  compartment_id = var.oci_compartment_ocid
  vcn_id         = oci_core_vcn.this.id
  display_name   = "oci-aws-rt"

  route_rules {
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.igw.id
  }
  route_rules {
    destination       = var.aws_vpc_cidr
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_drg.this.id
  }

  depends_on = [oci_core_drg_attachment.vcn]
}

resource "oci_core_security_list" "vm" {
  compartment_id = var.oci_compartment_ocid
  vcn_id         = oci_core_vcn.this.id
  display_name   = "oci-aws-sl"

  egress_security_rules {
    destination = "0.0.0.0/0"
    protocol    = "all"
  }
  ingress_security_rules {
    source   = var.my_ip_cidr
    protocol = "6" # TCP
    tcp_options {
      min = 22
      max = 22
    }
  }
  ingress_security_rules {
    source   = var.aws_vpc_cidr
    protocol = "1" # ICMP
  }
}

resource "oci_core_subnet" "public" {
  compartment_id    = var.oci_compartment_ocid
  vcn_id            = oci_core_vcn.this.id
  cidr_block        = var.oci_subnet_cidr
  display_name      = "oci-aws-public"
  route_table_id    = oci_core_route_table.public.id
  security_list_ids = [oci_core_security_list.vm.id]
}

# ---------------- Site-to-Site VPN ----------------
# CPE = AWS tunnel 1 public endpoint
resource "oci_core_cpe" "aws" {
  compartment_id = var.oci_compartment_ocid
  ip_address     = aws_vpn_connection.to_oci.tunnel1_address
  display_name   = "aws-cpe"
}

resource "oci_core_ipsec" "to_aws" {
  compartment_id = var.oci_compartment_ocid
  cpe_id         = oci_core_cpe.aws.id
  drg_id         = oci_core_drg.this.id
  static_routes  = [var.aws_vpc_cidr]
  display_name   = "oci-to-aws-vpn"
}

data "oci_core_ipsec_connection_tunnels" "t" {
  ipsec_id = oci_core_ipsec.to_aws.id
}

# Tunnel [0] is paired with AWS tunnel 1. Settings mirror aws.tf exactly.
resource "oci_core_ipsec_connection_tunnel_management" "t1" {
  ipsec_id            = oci_core_ipsec.to_aws.id
  tunnel_id           = data.oci_core_ipsec_connection_tunnels.t.ip_sec_connection_tunnels[0].id
  display_name        = "tunnel-1-aws"
  routing             = "STATIC"
  ike_version         = "V2"
  shared_secret       = local.psk
  oracle_can_initiate = "INITIATOR_OR_RESPONDER"

  phase_one_details {
    is_custom_phase_one_config      = true
    custom_encryption_algorithm     = "AES_256_CBC"
    custom_authentication_algorithm = "SHA2_256"
    custom_dh_group                 = "GROUP14"
    lifetime                        = 28800
  }

  phase_two_details {
    is_custom_phase_two_config      = true
    custom_encryption_algorithm     = "AES_256_CBC" # default is GCM -> mismatched AWS
    custom_authentication_algorithm = "HMAC_SHA2_256_128"
    is_pfs_enabled                  = true
    dh_group                        = "GROUP14" # default GROUP5 -> mismatched AWS
    lifetime                        = 3600
  }
}

# ---------------- Test VM ----------------
resource "oci_core_instance" "vm" {
  compartment_id      = var.oci_compartment_ocid
  availability_domain = data.oci_identity_availability_domains.ads.availability_domains[0].name
  display_name        = "oci-vm"
  shape               = var.oci_shape

  dynamic "shape_config" {
    for_each = local.is_flex ? [1] : []
    content {
      ocpus         = 1
      memory_in_gbs = 4
    }
  }

  source_details {
    source_type = "image"
    source_id   = data.oci_core_images.ol8.images[0].id
  }

  create_vnic_details {
    subnet_id        = oci_core_subnet.public.id
    assign_public_ip = true
  }

  metadata = {
    ssh_authorized_keys = var.ssh_public_key
    # Oracle Linux's firewalld blocked ICMP in the manual build; disabled here (lab only)
    user_data = base64encode(<<-CLOUDINIT
      #!/bin/bash
      systemctl disable --now firewalld || true
    CLOUDINIT
    )
  }
}
